package com.fxd927.mekanismelements.common.datagen;

import com.fxd927.mekanismelements.common.MekanismElements;
import com.fxd927.mekanismelements.common.registries.MSBlocks;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.neoforged.neoforge.common.data.BlockTagsProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;

import java.util.concurrent.CompletableFuture;

public class MSBlockTagsProvider extends BlockTagsProvider {

    public MSBlockTagsProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, MekanismElements.MODID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {
        tag(BlockTags.MINEABLE_WITH_PICKAXE)
                .add(MSBlocks.ADSORPTION_SEPARATOR.get())
                .add(MSBlocks.AIR_COMPRESSOR.get())
                .add(MSBlocks.RADIATION_IRRADIATOR.get())
                .add(MSBlocks.SEAWATER_PUMP.get())
                .add(MSBlocks.HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.AQUA_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.BLACK_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.BLUE_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.GREEN_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.CYAN_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.DARK_RED_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.PURPLE_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.ORANGE_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.LIGHT_GRAY_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.GRAY_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.LIGHT_BLUE_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.LIME_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.RED_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.MAGENTA_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.YELLOW_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.WHITE_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.BROWN_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.PINK_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.AQUA_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.BLACK_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.BLUE_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.GREEN_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.CYAN_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.DARK_RED_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.PURPLE_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.ORANGE_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.LIGHT_GRAY_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.GRAY_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.LIGHT_BLUE_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.LIME_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.RED_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.MAGENTA_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.YELLOW_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.WHITE_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.BROWN_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.PINK_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.AQUA_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.BLACK_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.BLUE_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.GREEN_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.CYAN_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.DARK_RED_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.PURPLE_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.ORANGE_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.LIGHT_GRAY_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.GRAY_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.LIGHT_BLUE_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.LIME_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.RED_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.MAGENTA_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.YELLOW_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.WHITE_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.BROWN_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.PINK_HIGH_QUALITY_CONCRETE_SLABS.get());
     
        tag(BlockTags.NEEDS_IRON_TOOL)
                .add(MSBlocks.ADSORPTION_SEPARATOR.get())
                .add(MSBlocks.AIR_COMPRESSOR.get())
                .add(MSBlocks.RADIATION_IRRADIATOR.get())
                .add(MSBlocks.SEAWATER_PUMP.get())
                .add(MSBlocks.HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.AQUA_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.BLACK_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.BLUE_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.GREEN_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.CYAN_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.DARK_RED_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.PURPLE_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.ORANGE_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.LIGHT_GRAY_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.GRAY_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.LIGHT_BLUE_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.LIME_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.RED_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.MAGENTA_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.YELLOW_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.WHITE_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.BROWN_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.PINK_HIGH_QUALITY_CONCRETE.get())
                .add(MSBlocks.HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.AQUA_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.BLACK_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.BLUE_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.GREEN_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.CYAN_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.DARK_RED_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.PURPLE_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.ORANGE_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.LIGHT_GRAY_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.GRAY_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.LIGHT_BLUE_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.LIME_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.RED_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.MAGENTA_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.YELLOW_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.WHITE_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.BROWN_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.PINK_HIGH_QUALITY_CONCRETE_STAIRS.get())
                .add(MSBlocks.HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.AQUA_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.BLACK_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.BLUE_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.GREEN_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.CYAN_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.DARK_RED_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.PURPLE_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.ORANGE_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.LIGHT_GRAY_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.GRAY_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.LIGHT_BLUE_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.LIME_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.RED_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.MAGENTA_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.YELLOW_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.WHITE_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.BROWN_HIGH_QUALITY_CONCRETE_SLABS.get())
                .add(MSBlocks.PINK_HIGH_QUALITY_CONCRETE_SLABS.get());


        tag(BlockTags.NEEDS_DIAMOND_TOOL)
                .add(MSBlocks.ADSORPTION_SEPARATOR.get())
                .add(MSBlocks.AIR_COMPRESSOR.get())
                .add(MSBlocks.RADIATION_IRRADIATOR.get())
                .add(MSBlocks.SEAWATER_PUMP.get());
    }
}